name: lingo_hunter
description: LingoHunter is a powerful Dart package designed to automatically extract translatable strings from Flutter projects and generate JSON translation files. This helps developers streamline their localization process efficiently.
version: 1.0.3
repository: https://github.com/fares-Mondriod/Lingo-Hunter

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0

executables:
  lingo_hunter: bin/lingo_hunter.dart

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
